updated the workflow

diff --git a/spring-boot-backend-helm-chart/templates/analysis-template.yaml b/spring-boot-backend-helm-chart/templates/analysis-template.yaml
--- a/spring-boot-backend-helm-chart/templates/analysis-template.yaml
+++ b/spring-boot-backend-helm-chart/templates/analysis-template.yaml
@@ -11,9 +11,13 @@ metadata:
 spec:
   metrics:
     - name: endpoint-test
+      #failureLimit: 4
       provider:
         job:
           spec:
+            ttlSecondsAfterFinished: 300  # Job will be deleted 5 minutes after finishing
+            backoffLimit: 3
+            activeDeadlineSeconds: 150  # Set the time in seconds before which the job should not end
             template:
               metadata:
                 labels:
@@ -42,45 +46,39 @@ spec:
 
                         # Directly test the endpoint with headers
                         echo "Directly testing the endpoint..."
-                        endpoint_response=$(curl -fs -H "Accept: application/json" -o response_body.txt -w "%{http_code}" -X GET "http://backend-spring-app.com/spring-app/")
-                        endpoint_body=$(<response_body.txt)
-
-                        echo "Endpoint Response Code: $endpoint_response"
-                        echo "Endpoint Response Body: $endpoint_body"
+                        endpoint_response=$(curl -fs -H "Accept: application/json" "http://backend-spring-app.com/spring-app/")
+                        echo "Endpoint Response: $endpoint_response"
 
                         # Check if the response is empty
-                        if [ -z "$endpoint_body" ]; then
+                        if [ -z "$endpoint_response" ]; then
                           echo "Received an empty response body from http://backend-spring-app.com/spring-app/"
                         fi
 
                         # Check the expected responses
                         check_endpoint() {
-                          expected_status="$1"
-                          expected_response="$2"
-                          url="$3"
-                          response=$(curl -fs -H "Accept: application/json" -o response_body.txt -w "%{http_code}" -X GET "$url" || echo "Curl failed")
-                          body=$(<response_body.txt)
+                          expected_response="$1"
+                          url="$2"
 
-                          echo "Response code: $response"
-                          echo "Response body: $body"
+                          # Get the response directly
+                          response=$(curl -fs "$url" || echo "Curl failed")
 
-                          if [ "$response" != "$expected_status" ]; then
-                            echo "Test failed for $url: Expected status '$expected_status' but got '$response'"
-                            exit 1  # Fail the job
-                          elif [ "$body" != "$expected_response" ]; then
-                            echo "Test failed for $url: Expected response '$expected_response' but got '$body'"
+                          echo "Response: $response"
+
+                          # Check if the response matches the expected response
+                          if [ "$response" != "$expected_response" ]; then
+                            echo "Test failed for $url: Expected response '$expected_response' but got '$response'"
                             exit 1  # Fail the job
                           else
-                            echo "Test passed for $url: Received status '$response' and body '$body'"
+                            echo "Test passed for $url: Received expected response '$response'"
                           fi
                         }
 
                         echo "Testing additional endpoints..."
-                        check_endpoint "200" '{"status":"200","message":"WELCOME"}' "http://backend-spring-app.com/spring-app/"
-                        check_endpoint "201" '{"status":"201","message":"CREATED"}' "http://backend-spring-app.com/spring-app/resource-created"
-                        check_endpoint "202" '{"status":"202","message":"ACCEPTED"}' "http://backend-spring-app.com/spring-app/resource-accepted"
-                        check_endpoint "406" '{"status":"406","message":"NOT_ACCEPTABLE"}' "http://backend-spring-app.com/spring-app/resource-not-acceptable"
-                        check_endpoint "501" '{"status":"501","message":"NOT_IMPLEMENTED"}' "http://backend-spring-app.com/spring-app/resource-not-implemented"
-                        
+                        check_endpoint '{"status":"200","message":"WELCOME"}' "http://backend-spring-app.com/spring-app/"
+                        check_endpoint '{"status":"201","message":"CREATED"}' "http://backend-spring-app.com/spring-app/resource-created"
+                        check_endpoint '{"status":"202","message":"ACCEPTED"}' "http://backend-spring-app.com/spring-app/resource-accepted"
+                        #check_endpoint '{"status":"406","message":"NOT_ACCEPTABLE"}' "http://backend-spring-app.com/spring-app/resource-not-acceptable"
+                        #check_endpoint '{"status":"501","message":"NOT_IMPLEMENTED"}' "http://backend-spring-app.com/spring-app/resource-not-implemented"
+                      
                         echo "All tests completed."
                 restartPolicy: Never
