updating workflow[skip actions]

diff --git a/.github/workflows/deploy-canary.yml b/.github/workflows/deploy-canary.yml
--- a/.github/workflows/deploy-canary.yml
+++ b/.github/workflows/deploy-canary.yml
@@ -77,7 +77,17 @@ jobs:
         run: |
           helm upgrade --install rollouts-spring-release ./spring-boot-helm-chart-argo-rollout --create-namespace --namespace rollouts-spring --values=./spring-boot-helm-chart-argo-rollout/values.yaml  --force
 
-      # Step to print the rollout status.
-      # This step checks and prints the status of the rollout to verify if the rollback was successful.
-      - name: Print Rollout Status
-        run: kubectl argo rollouts get rollout rollouts-spring-release-rollouts --namespace=rollouts-spring
+      - name: Monitor Rollout Status
+        run: |
+          while true; do
+            status=$(kubectl argo rollouts get rollout rollouts-spring-release-rollouts --namespace=rollouts-spring -o json | jq -r '.status.phase')
+            echo "Current rollout status: $status"
+            if [[ "$status" == "Healthy" ]]; then
+              echo "Rollout completed successfully."
+              exit 0
+            elif [[ "$status" == "Degraded" ]]; then
+              echo "Rollout failed."
+              exit 1
+            fi
+            sleep 30
+          done
